### ISSUE TITLE
Entering a URL that has a space in it does not provide any feedback to user and fails later when trying 

### ISSUE THREAD

**Issue by mkobit** [topicusfinan/bitbucket-webhooks-plugin#18]
It doesn't provide feedback to the user but fails later when an event is attempted to be created.

```
2017-01-23 01:26:59,431 ERROR [AtlassianEvent::thread-4] username @16LCDKJx86x29721555x0 oew3e4 10.26.200.99 SSH - git-receive-pack '/mon/metrics-consumer.git' c.a.s.i.e.AsyncBatchingInvokersTransformer There was an exception thrown trying to dispatch event 'com.atlassian.bitbucket.event.repository.RepositoryPushEvent[source=com.atlassian.stash.internal.hook.PushPostReceiveHook@783a1115]' for the invoker 'SingleParameterMethodListenerInvoker{method=public void nl.topicus.bitbucket.api.PullRequestListener.repoChangedEvent(com.atlassian.bitbucket.event.repository.AbstractRepositoryRefsChangedEvent) throws java.io.IOException, listener=nl.topicus.bitbucket.api.PullRequestListener@5a6c59}'
java.lang.RuntimeException: Illegal character in path at index 60: http://ourjenkinsinstance.com/bitbucket-scmsource-hook/notify . Listener: nl.topicus.bitbucket.api.PullRequestListener event: com.atlassian.bitbucket.event.repository.RepositoryPushEvent
        at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:55) ~[atlassian-event-3.1.3.jar:na]
        at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:109) ~[bitbucket-platform-4.11.1.jar:na]
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:38) [atlassian-event-3.1.3.jar:na]
        at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34) [sal-core-3.0.6.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
        ... 1 frame trimmed
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 60: http://ourjenkinsinstance.com/bitbucket-scmsource-hook/notify
        at java.net.URI.create(URI.java:852) ~[na:1.8.0_101]
        at com.atlassian.httpclient.base.AbstractHttpClient.newRequest(AbstractHttpClient.java:37) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) ~[na:na]
        at nl.topicus.bitbucket.api.PullRequestListener.sendEvents(PullRequestListener.java:106) ~[na:na]
        at nl.topicus.bitbucket.api.PullRequestListener.repoChangedEvent(PullRequestListener.java:84) ~[na:na]
        at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:40) ~[atlassian-event-3.1.3.jar:na]
        ... 6 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in path at index 60: http://ourjenkinsinstance.com/bitbucket-scmsource-hook/notify
        at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_101]
        at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_101]
        at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[na:1.8.0_101]
        at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_101]
        at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_101]
        at java.net.URI.create(URI.java:850) ~[na:1.8.0_101]
        ... 15 common frames omitted
```

**Comment by mkobit** [comment]
That happened with I think `1.1.0`, we just updated to `1.2.0`

**Comment by Eernie** [comment]
Yes you're correct, There isn't any input validation yet. 
I'll try to implement this in the near future
